CUDA_VISIBLE_DEVICES=0 python train.py --model HADARNet \
--smp_model Unet --smp_encoder resnet18 --smp_encoder_weights imagenet \
--num-epochs 950 \
--num-epochs-save 10 \
--num-epochs-val 10 \
--losstype hadarloss \
--outputs-dir ./experiments/Unet_res18_imagenet \
--batch-size 64 \
--lr 0.000001 \
--train-file data/flir_train.h5 \
--eval-file data/flir_val.h5